[package]
name = "reth-scroll-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-primitives.workspace = true

# reth
reth-codecs = { workspace = true, optional = true }

# scroll
poseidon-bn254 = { workspace = true, features = ["bn254"], optional = true }

# required by reth-codecs
modular-bitfield = { workspace = true, optional = true }
serde.workspace = true

# misc
arbitrary = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
alloy-primitives = { workspace = true, features = ["arbitrary"] }
arbitrary = { workspace = true, features = ["derive"] }
reth-codecs = { workspace = true, features = ["test-utils"] }

test-fuzz.workspace = true

[features]
default = [
    "reth-codec",
    "std"
]
std = [
    "serde/std",
    "alloy-primitives/std",
    "reth-codecs/std",
]
arbitrary = [
    "dep:arbitrary",
    "alloy-primitives/arbitrary",
    "reth-codecs/arbitrary"
]
reth-codec = [
    "dep:reth-codecs",
    "modular-bitfield",
    "std"
]
serde = [
    "alloy-primitives/serde",
    "reth-codecs/serde"
]
poseidon = ["dep:poseidon-bn254"]
