[package]
name = "reth-scroll-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-db.workspace = true
reth-consensus.workspace = true
reth-ethereum-engine-primitives.workspace = true
reth-ethereum-forks.workspace = true
reth-evm.workspace = true
reth-network.workspace = true
reth-node-api.workspace = true
reth-node-types.workspace = true
reth-node-builder.workspace = true
reth-payload-builder = { workspace = true, features = ["test-utils"] }
reth-primitives.workspace = true
reth-primitives-traits.workspace = true
reth-provider.workspace = true
reth-rpc.workspace = true
reth-tracing.workspace = true
reth-transaction-pool.workspace = true
reth-trie-db.workspace = true

# alloy
alloy-rpc-types-engine.workspace = true

# scroll
reth-scroll-chainspec.workspace = true
reth-scroll-evm.workspace = true
reth-scroll-state-commitment.workspace = true

# alloy
alloy-primitives.workspace = true

# misc
eyre.workspace = true
tokio.workspace = true

[features]
optimism = [
	"reth-db/optimism",
	"reth-primitives/optimism",
	"reth-provider/optimism",
	"reth-scroll-evm/optimism"
]
scroll = [
	"reth-db/scroll",
	"reth-node-builder/scroll",
	"reth-primitives/scroll",
	"reth-provider/scroll",
	"reth-evm/scroll",
	"reth-scroll-state-commitment/scroll",
	"reth-scroll-evm/scroll",
]