[package]
name = "reth-scroll-encoder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Zstd encoder implementation for scroll."

[lints]
workspace = true

[dependencies]
zstd = { git = "https://github.com/scroll-tech/zstd-rs", branch = "hack/mul-block", features = ["experimental"]}