[package]
name = "scroll-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-cli-util.workspace = true
reth-node-builder.workspace = true
reth-provider.workspace = true

# scroll
reth-scroll-cli.workspace = true
reth-scroll-node.workspace = true

# misc
clap = { workspace = true, features = ["derive", "env"] }

[features]
scroll = [
	"reth-node-builder/scroll",
	"reth-provider/scroll",
	"reth-scroll-cli/scroll"
]
optimism = [
	"reth-provider/optimism",
	"reth-scroll-cli/optimism",
	"reth-scroll-node/optimism"
]

[[bin]]
name = "scroll-reth"
path = "src/main.rs"