[package]
name = "reth-scroll-state-commitment"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
reth-db = { workspace = true, features = ["test-utils"] }
reth-execution-errors.workspace = true
reth-primitives.workspace = true
reth-primitives-traits = { workspace = true }
reth-scroll-execution.workspace = true
reth-scroll-primitives.workspace = true
reth-scroll-trie.workspace = true
reth-trie = { workspace = true }
reth-trie-db.workspace = true

# alloy
alloy-consensus = { workspace = true, optional = true}
alloy-primitives.workspace = true
alloy-rlp.workspace = true

# `metrics` feature
reth-metrics = { workspace = true, optional = true }
metrics = { workspace = true, optional = true }

# zktrie
poseidon-bn254.workspace = true
zktrie_rust = { git = "https://github.com/scroll-tech/zktrie.git", rev = "309160464c1cd2b87a578ed6d9b6e98205ae4640", optional = true }
zktrie = { git = "https://github.com/scroll-tech/zktrie.git", rev = "309160464c1cd2b87a578ed6d9b6e98205ae4640", features = ["rs_zktrie"], optional = true }

# misc
tracing.workspace = true

[dev-dependencies]
reth-db-api.workspace = true
reth-primitives = { workspace = true, features = ["test-utils", "arbitrary"] }
reth-scroll-state-commitment = { workspace = true, features = ["test-utils"]}
reth-trie = { workspace = true, features = ["test-utils" ] }
reth-trie-common = { workspace = true, features = ["test-utils", "arbitrary"] }
reth-provider = { workspace = true, features = ["test-utils" ] }
alloy-consensus.workspace = true
zktrie_rust = { git = "https://github.com/scroll-tech/zktrie.git", rev = "309160464c1cd2b87a578ed6d9b6e98205ae4640" }
zktrie = { git = "https://github.com/scroll-tech/zktrie.git", rev = "309160464c1cd2b87a578ed6d9b6e98205ae4640", features = ["rs_zktrie"] }
proptest.workspace = true
proptest-arbitrary-interop.workspace = true

[lints]
workspace = true

[features]
scroll = [
    "reth-trie/scroll",
    "reth-primitives-traits/scroll",
    "reth-provider/scroll",
    "reth-trie/scroll"
]
test-utils = [
    "dep:zktrie_rust", 
    "dep:zktrie", 
    "dep:alloy-consensus",
    "reth-db/test-utils",
    "reth-db-api/test-utils",
    "reth-primitives/test-utils",
    "reth-primitives-traits/test-utils",
    "reth-provider/test-utils",
    "reth-scroll-execution/test-utils",
    "reth-scroll-state-commitment/test-utils",
    "reth-trie/test-utils",
    "reth-trie-common/test-utils",
    "reth-trie-db/test-utils"
    ]
metrics = ["reth-metrics", "dep:metrics"]


